# Site settings
title: Brett's Site
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bbush.me" # the base hostname & protocol for your site
github_username:  brettjbush
pinterest_username:  brettjbush
spotify_username:  1214399655
linkedin_username:  brett-bush-6a1500b0

# Build settings
markdown: kramdown

# Central Time Zone
timezone: America/Chicago

# Set path as title
permalink: /:categories/:title/
